SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Comment;
TRUNCATE TABLE Ticket;
TRUNCATE TABLE User;
TRUNCATE TABLE StateType;
TRUNCATE TABLE Priority;
TRUNCATE TABLE RoleUser;

SET FOREIGN_KEY_CHECKS = 1;