CREATE DATABASE IF NOT EXISTS HELPDESK;
USE HELPDESK;

#have no dependencies
#statetype
#priority
#roleuser

#have dependencies in order
#user
#ticket
#comment

DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS RoleUser;
DROP TABLE IF EXISTS Priority;
DROP TABLE IF EXISTS StateType;


CREATE TABLE StateType(
    Id INT AUTO_INCREMENT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NameColor VARCHAR(20),

    PRIMARY KEY(Id)
) ENGINE=INNODB;

CREATE TABLE Priority(
    Id INT AUTO_INCREMENT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NamePriority VARCHAR(50),

    PRIMARY KEY(Id)
) ENGINE=INNODB;

CREATE TABLE RoleUser(
    Id INT AUTO_INCREMENT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NameRole VARCHAR(25),

    PRIMARY KEY(Id)
) ENGINE=INNODB;


CREATE TABLE User(
    Id INT AUTO_INCREMENT NOT NULL,
    RoleUserId INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    NameUser VARCHAR(25) NOT NULL,
    PasswordUser VARCHAR(256) NOT NULL,
    Account VARCHAR(50) NOT NULL,

    PRIMARY KEY(Id),
    INDEX RoleIndex (RoleUserId),
    FOREIGN KEY(RoleUserId) REFERENCES RoleUser(Id)
) ENGINE=INNODB;

CREATE TABLE Ticket(
    Id INT AUTO_INCREMENT NOT NULL,
    ResponsibleId INT NOT NULL,
    StateId INT NOT NULL,
    PriorityId INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Title VARCHAR(20),
    TimeStart DATETIME NOT NULL,
    PromiseEnd DATETIME NOT NULL,
    ClosedAt DATETIME DEFAULT NULL,
    Details VARCHAR(100),

    PRIMARY KEY(Id),
    INDEX ResponsibleIndex (ResponsibleId),
    FOREIGN KEY(ResponsibleId) REFERENCES User(Id),
    INDEX TypeIndex (StateId),
    FOREIGN KEY(StateId) REFERENCES StateType(Id),
    INDEX PriorityIndex (PriorityId),
    FOREIGN KEY(PriorityId) REFERENCES Priority(Id)

) ENGINE=INNODB;

CREATE TABLE Comment(
    Id INT AUTO_INCREMENT NOT NULL,
    UserId INT NOT NULL,
    TicketId INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ValueComment VARCHAR(100),

    PRIMARY KEY(Id),
    INDEX UserIndex (UserId),
    FOREIGN KEY(UserId) REFERENCES User(Id),
    INDEX TicketIndex (TicketId),
    FOREIGN KEY(TicketId) REFERENCES Ticket(Id)
) ENGINE=INNODB;